# Copyright iSynergy TechSys Pvt. Ltd.

from autogen import (
    AssistantAgent,
)

config_list = [
    {
        "model": "gpt-4",
        "api_key": "your-api-key-here",  # Insert your OpenAI API key.
    }
]

# create an AssistantAgent named "programmer_agent"
programmer = AssistantAgent(
    name="programmer_agent",
    system_message="""You are a programmer agent. Your task is to generate code that reads a file from a given location, where the file format may be CSV, TSV, Parquet, or XLSX. Based on the development environment specified (such as Databricks with PySpark, SQL-based environments like Microsoft SQL Server, Snowflake, Oracle, or AWS Glue), write the code in the appropriate language. Perform data wrangling tasks such as grouping, filtering, aggregation, and sorting. Return only the code, without any explanations or descriptions.""",
    is_termination_msg=lambda x: "TERMINATE" in x.get("content", "").rstrip(),
    llm_config={
        "config_list": config_list,  # a list of OpenAI API configurations
        "temperature": 0,  # temperature for sampling
    },
)

# create a UserProxyAgent instance named "tester_agent"
tester = AssistantAgent(
    name="tester_agent",
    system_message="""You are a testing agent. Your task is to analyze the code generated by the programmer agent. Inspect it for errors, such as incorrect syntax, logic flaws, or compatibility issues with the specified development environment. If the code is correct and error-free, return 'TERMINATE'. If there are any mistakes, provide clear feedback and suggest a fix.""",
    llm_config={
        "config_list": config_list,  # a list of OpenAI API configurations
        "temperature": 0,  # temperature for sampling
    },
)

chat_res = tester.initiate_chat(
    programmer,
    message="Generate PySpark code in Databricks that reads a Parquet file from /mnt/data/sample.parquet, groups by the 'Region' column, and returns the total sales in descending order.",
    summary_method="reflection_with_llm",
    max_turns=10,
)
